---

- name: "DB: get jobs from  Cronjob table"
  community.postgresql.postgresql_query:
     db:          "{{ db.database }}"
     login_host:  "{{ db.hostname }}"
     login_user:  "{{ db.username }}"
     login_password: "{{ db.pwd }}"
     query: "select * from nse.cronjobs a;"
  register: sq_result


- name: "Print jobs from  Cronjob"
  ansible.builtin.debug: 
     msg: "{{sq_result}}"
  when: debug


- name: "create CRON jobs"
  ansible.builtin.cron:
     name: "{{item.name}}"
     minute: "*/{{item.cron_exp}}"
     job: "{{ item.job }}"
     state: "{{ item.status }}"
  loop: "{{ sq_result.query_result|list }}"


- name: "print CRON jobs"
  ansible.builtin.command:
      argv: 
      - "crontab"
      - "-l"
  ignore_errors: true
  changed_when: false
  register: cron_op


- name: "Print Cron Jobs"
  ansible.builtin.debug:
      msg: "{{ cron_op.stdout_lines }}"
