---
- name: "Print paramaters for {{tsymbol}}"
  ansible.builtin.debug:
     msg: "from_date = {{ start_date }}, end_date={{ end_date }}, ticker = {{ ticker }}" 
  when: debug

- name: "NSE Home Page({{tsymbol}})"
  ansible.builtin.uri:
     url: "{{ nse_url }}"
     method: GET
     headers:
        User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"
        Accept-Encoding: "gzip, deflate, br"
     return_content: true
  register: homePage

- name: "Print NSE Home Page({{tsymbol}})"
  ansible.builtin.debug:
     msg: "{{ homePage.cookies_string }}"
  when: debug

- name: "NSE Lookup Company Page({{tsymbol}})"
  ansible.builtin.uri:
     url: "{{ nse_url }}/get-quotes/equity?symbol={{tsymbol }}"
     method: GET
     headers:
        User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"
        Referer: "{{ nse_url }}/"
        Cookie: "{{ homePage.cookies_string }}"
        Accept-Encoding: "gzip, deflate, br"
  register: lookupPage

- name: "Print NSE Lookup Company Page({{tsymbol}})"
  ansible.builtin.debug:
     msg: "{{ lookupPage }}"
  when: debug

- name: "NSE Lookup Company Page2({{tsymbol}})"
  ansible.builtin.uri:
     url: "{{ nse_url }}/get-quotes/equity?symbol={{tsymbol }}"
     method: GET
     headers:
        User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"
        Referer: "{{ nse_url }}/"
        Connection: "keep-alive"
        Cookie: "{{ lookupPage.cookies_string }}"
        Accept-Encoding: "gzip, deflate, br"
        Upgrade-Insecure-Requests: 1
        Sec-Fetch-Dest: "document"
        Sec-Fetch-Mode: "navigate"
        Sec-Fetch-Site: "same-origin"
        Sec-Fetch-User: "?1"
        TE: "trailers"
  register: lookupPage2

- name: "Print NSE Lookup Company Page2({{tsymbol}})"
  ansible.builtin.debug:
     msg: "{{ lookupPage2 }}"
  when: debug


- name: "NSE Get Data Page({{tsymbol}})"
  ansible.builtin.uri:
     url: "{{ nse_url }}/api/historical/cm/equity?symbol={{tsymbol }}&series=[%22EQ%22]&from={{ start_date }}&to={{ end_date }}"
     method: GET
     headers:
        User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"
        Referer: "{{ nse_url }}/get-quotes/equity?symbol={{ tsymbol }}"
        Cookie: "{{ lookupPage2.cookies_string }}"
        Accept-Encoding: "gzip, deflate, br"
  register: dataPage

- name: "Print NSE Get Data Page({{tsymbol}})"
  ansible.builtin.debug:
     msg: "{{ dataPage.cookies_string }}"
  when: debug

- name: "NSE Get CSV Page({{tsymbol}})"
  ansible.builtin.uri:
     url: "{{ nse_url }}/api/historical/cm/equity?symbol={{tsymbol }}&series=[%22EQ%22]&from={{ start_date }}&to={{ end_date }}&csv=true"
     method: GET
     return_content: true
     headers:
        User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        Accept: "*/*"
        Accept-Language: "en-US,en;q=0.5"
        Referer: "{{ nse_url }}/get-quotes/equity?symbol={{ tsymbol }}"
        Cookie: "{{ dataPage.cookies_string }};{{ lookupPage2.cookies_string }}"
        Accept-Encoding: ""
        Connection: "keep-alive"
        DNT: "1"
        Sec-GPC: "1"
        Sec-Fetch-Dest: "empty"
        Sec-Fetch-Mode: "cors"
        Sec-Fetch-Site: "same-origin"
        TE: "trailers"
  register: csvdataPage

#        - name: "Print NSE Get CSV Page"
#          ansible.builtin.debug:
#             msg: "{{ csvdataPage.content }}"
#          when: debug


#        - name: "Print NSE Get CSV Page"
#          ansible.builtin.debug:
#             msg: "({{ item }})"
#          loop: "{{ csvdataPage.content.split('\n')}}"
#          when: debug

#- name: "Print NSE Get CSV Page"
#  ansible.builtin.debug:
#     msg: "insert into temp_table({{ csvdataPage.content.split('\n')| join('),(') }}); "

- name: "create stock price insert script for {{tsymbol}}"
  ansible.builtin.template:
     src: "load_stock_price.csv.j2"
     dest: "output/load_stock_price_{{tsymbol}}_{{start_date}}_{{end_date}}.sql"
#  when: var_lc_stock_details.rowcount  > 0

- name: "DB: load_stock_price for {{ tsymbol }} for dates {{ start_date }}<< = >>{{ end_date }}"
  community.postgresql.postgresql_script:
     db:          "{{ db.database }}"
     login_host:  "{{ db.hostname }}"
     login_user:  "{{ db.username }}"
     login_password: "{{ db.pwd }}"
     path: "output/load_stock_price_{{tsymbol}}_{{start_date}}_{{end_date}}.sql"
  register: dbResult0

- name: "DB: update lc_stock_details for {{ tsymbol }} for dates {{ start_date }}<< = >>{{ end_date }}"
  community.postgresql.postgresql_query:
     db:          "{{ db.database }}"
     login_host:  "{{ db.hostname }}"
     login_user:  "{{ db.username }}"
     login_password: "{{ db.pwd }}"
     query: "update nse.load_bulk_stock_dates set is_loaded=true where ticker='{{tsymbol}}' and  to_char(start_date,'DD-MM-YYYY')='{{start_date}}' and to_char(end_date,'DD-MM-YYYY')='{{end_date}}' "
  register: dbResult1

- name: pause
  ansible.builtin.pause:
     seconds: "2"
