---
- name: "DSP NSE Home Page({{tsymbol}})"
  ansible.builtin.uri:
     url: "{{ nse_url }}"
     method: GET
     headers:
        User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"
        Accept-Encoding: "gzip, deflate, br"
     return_content: true
  register: homePage

- name: "Print DSP NSE Home Page({{tsymbol}})"
  ansible.builtin.debug:
     msg: "{{ homePage.cookies_string }}"
  when: debug

- name: "DSP NSE Lookup Company Page({{tsymbol}})"
  ansible.builtin.uri:
     url: "{{ nse_url }}/get-quotes/equity?symbol={{tsymbol }}"
     method: GET
#     return_content: true
     headers:
        User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"
        Referer: "{{ nse_url }}/"
        Cookie: "{{ homePage.cookies_string }}"
        Accept-Encoding: "gzip, deflate, br"
#        Accept-Encoding: "*"
  register: lookupPage

- name: "Print DSP NSE Lookup Company Page({{tsymbol}})"
  ansible.builtin.debug:
     msg: "{{ lookupPage }}"
  when: debug

- name: "DSP NSE Company Info({{tsymbol}})"
  ansible.builtin.uri:
     url: "{{ nse_url }}/api/quote-equity?symbol={{tsymbol }}"
     method: GET
     return_content: true
     headers:
        User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"
        Referer: "{{ nse_url }}/"
        Cookie: "{{ homePage.cookies_string }};{{ lookupPage.cookies_string }}"
        Accept-Encoding: "*"
  register: companyPage

- name: "Print DSP NSE Company Info({{tsymbol}})"
  ansible.builtin.debug:
     msg: "{{ companyPage }}"
  when: debug 

- name: "Print DSP cookie({{tsymbol}})"
  ansible.builtin.debug:
     msg: "{{homePage.cookies_string}};{{lookupPage.cookies_string}};{{ companyPage.cookies_string }}"
  when: debug

- name: "DSP NSE Company Trade Info({{tsymbol}})"
  ansible.builtin.uri:
     url: "{{ nse_url }}/api/quote-equity?symbol={{tsymbol }}&section=trade_info"
     method: GET
     return_content: true
     headers:
        User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
        Accept-Language: "en-US,en;q=0.5"
        Referer: "{{ nse_url }}/get-quotes/equity?symbol={{tsymbol }}"
        Cookie: "{{homePage.cookies_string}};{{lookupPage.cookies_string}};{{ companyPage.cookies_string }}"
        Accept-Encoding: "*"
  register: companyTradePage

- name: "Print DSP NSE Company Trade Info({{tsymbol}})"
  ansible.builtin.debug:
     msg: "{{ companyTradePage }}"
  when: debug

#- name: "Print DSP NSE Company Trade Info({{tsymbol}})"
#  ansible.builtin.debug:
#     msg: "{{ companyPage.json }}-------------{{companyTradePage.json}}"
##  when: debug

- name: "Print DSP NSE Company Page Info({{tsymbol}})"
  ansible.builtin.debug:
     msg:
        - "info          = {{ companyPage | json_query('*.info') }}"
        - "metadata      = {{ companyPage | json_query('*.metadata') }}"
        - "securityInfo  = {{ companyPage | json_query('*.securityInfo') }}"
        - "sddDetails    = {{ companyPage | json_query('*.sddDetails') }}"
        - "priceInfo     = {{ companyPage | json_query('*.priceInfo') }}"
        - "industryInfo  = {{ companyPage | json_query('*.industryInfo') }}"
        - "preOpenMarket = {{ companyPage | json_query('*.preOpenMarket') }}"

- name: "Print DSP NSE Company Trade Page Info({{tsymbol}})"
  ansible.builtin.debug:
     msg:
        - "bulkBlockDeals      = {{ companyTradePage | json_query('*.bulkBlockDeals') }}"
        - "marketDeptOrderBook = {{ companyTradePage | json_query('*.marketDeptOrderBook') }}"
        - "securityWiseDP      = {{ companyTradePage | json_query('*.securityWiseDP') }}"

- name: "build variables ({{tsymbol}})"
  ansible.builtin.set_fact:
     _info                : "{{ companyPage | json_query('*.info') | to_json }}"
     _metadata            : "{{ companyPage | json_query('*.metadata') | to_json }}"
     _securityInfo        : "{{ companyPage | json_query('*.securityInfo') | to_json }}"
     _sddDetails          : "{{ companyPage | json_query('*.sddDetails') | to_json }}"
     _priceInfo           : "{{ companyPage | json_query('*.priceInfo') | to_json }}"
     _industryInfo        : "{{ companyPage | json_query('*.industryInfo')  | to_json}}"
     _preOpenMarket       : "{{ companyPage | json_query('*.preOpenMarket') | to_json }}"
     _bulkBlockDeals      : "{{ companyTradePage | json_query('*.bulkBlockDeals') | to_json }}"
     _marketDeptOrderBook : "{{ companyTradePage | json_query('*.marketDeptOrderBook') | to_json }}"
     _securityWiseDP      : "{{ companyTradePage | json_query('*.securityWiseDP') | to_json }}"

- name: "DB: load_daiy_stock_price for {{ tsymbol }}"
  community.postgresql.postgresql_query:
     db:          "{{ db.database }}"
     login_host:  "{{ db.hostname }}"
     login_user:  "{{ db.username }}"
     login_password: "{{ db.pwd }}"
     query: |
        insert into load_daily_stock_price(
        ticker, price_date, info, metadata, security_info, sdd_details,
        price_info, industry_info, preopen_market, bulk_block_deals, market_dept_order_book,
        security_wise_dp, crd_date,upd_date, crd_by, upd_by)
        values( '{{ tsymbol }}','yyyy/mm/dd', '{{ _info }}', '{ _metadata }}', '{{ _securityInfo }}', '{{ _sddDetails }}',
        '{{ _priceInfo }}', '{{ _industryInfo }}', '{{ _preOpenMarket }}', '{{ _bulkBlockDeals }}', '{{ _marketDeptOrderBook }}',
        '{{ _securityWiseDP }}',current_timestamp, current_timestamp, 'admin','admin');
  register: dbResult0

- name: "DB: update load_daily_stock_dates.is_loaded for {{ tsymbol }}"
  community.postgresql.postgresql_query:
     db:          "{{ db.database }}"
     login_host:  "{{ db.hostname }}"
     login_user:  "{{ db.username }}"
     login_password: "{{ db.pwd }}"
     query: "update nse.load_daily_stock_dates set is_loaded=true where ticker='{{tsymbol}}' and  to_char(price_date,'DD-MM-YYYY')=to_char(current_timestamp,'DD-MM-YYYY') "
  register: dbResult1

- name: pause
  ansible.builtin.pause:
     seconds: "2"
