---
  - name: Deploym script
    hosts: localhost
    gather_facts: no
    vars_files:
       - secrets.yml
    vars:
       - debug: false
       - job_name: "deployer.yml"
       - job_id: "{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
       - temp: "insert into nse.cronjobs(name,type,cron_exp,job,total_loads,pending_loads,status,crd_by,upd_by)values("

    tasks:

       - name: "start audit log"
         ansible.builtin.include_tasks:
            file: "suppl/common_audit.yml"
         vars:
            - condition: "start"

#       - name: "stop audit log"
#         ansible.builtin.include_tasks:
#            file: "suppl/common_audit.yml"
#         vars:
#            - condition: "stop"

       - name: Print Directories & Files
         ansible.builtin.debug:
            msg: "<<<=== dirs ===>>>{{ app_dirs }} <<<=== files ===>>> {{ app_files }}"

       - name: Create Directories
         ansible.builtin.file:
            path: "{{ item.name }}"
            state: "{{item.state}}"
         loop: "{{app_dirs }}"

       - name: "Copy files"
         ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
         loop: "{{ app_files }}"

       - name: "create CRON jobs script files"
         ansible.builtin.template:
             src: "{{item.src}}"
             dest: "{{item.dest}}"
             mode: "0700"
         loop: "{{cronscripts}}"

       - name: "load persistant cron jobs"
         community.postgresql.postgresql_query:
             db:          "{{ db.database }}"
             login_host:  "{{ db.hostname }}"
             login_user:  "{{ db.username }}"
             login_password: "{{ db.pwd }}"
             query: |
                insert into nse.cronjobs(name,type,cron_exp,job,total_loads,pending_loads,status,crd_by,upd_by,upd_date)values(
                   '{{ item.name}}'     , 
                   '{{ item.type}}',
                   '{{ item.cron_exp}}' , 
                   '{{ item.job }}'   ,
                   '{{ item.total_loads}}',
                   '{{ item.pending_loads}}',
                   'present',
                   'admin',
                   'admin',
                   current_timestamp)
                on conflict(name) do update
                   set type = EXCLUDED.type,
                   cron_exp = EXCLUDED.cron_exp,
                   job      = EXCLUDED.job,
                   total_loads = EXCLUDED.total_loads,
                   pending_loads = EXCLUDED.pending_loads,
                   status = EXCLUDED.status,
                   crd_by = EXCLUDED.crd_by,
                   upd_by = EXCLUDED.upd_by,
                   upd_date = EXCLUDED.upd_date;
         loop: "{{persistent_crons}}"

       - name: "Update & List CRON jobs"
         ansible.builtin.include_tasks:
            file: suppl/common_list_cronjob.yml


       - name: "start audit log"
         ansible.builtin.include_tasks:
            file: "suppl/common_audit.yml"
         vars:
            - condition: "stop"
