
---
  - name: NSE datadump
    hosts: localhost
    gather_facts: false
    vars_files:
        - secrets.yml
    vars:
        - ticker_nse_url: "https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv"
        - debug: false
        - job_name: "loadTickerTable.yml"
        - output: "{{directory.output}}"

    tasks:
        - name: "start audit log"
          ansible.builtin.include_tasks:
             file: "suppl/common_audit.yml"
          vars:
             - condition: "start"

        - name: NSE ticker list
          ansible.builtin.uri:
             url: "{{ nse.tickerList.url }}"
             method: GET
             headers:
                User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"
                Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
                Accept-Language: "en-US,en;q=0.5"
                Accept-Encoding: ""
             return_content: true
          register: var_tickers

        - name: "Print NSE ticker list"
          ansible.builtin.debug:
             msg: "{{ var_tickers }}"
          when: debug

        - name: "Create ticker csv file"
          ansible.builtin.template:
             src: "tickers.csv.j2"
             dest: "{{output}}/tickers.sql"
          when: var_tickers.status == 200

        - name: "DB: Load ticker list"
          community.postgresql.postgresql_script:
             db:          "{{ db.database }}"
             login_host:  "{{ db.hostname }}"
             login_user:  "{{ db.username }}"
             login_password: "{{ db.pwd }}"
             path: "{{output}}/tickers.sql"
          register: db_results0
          when: var_tickers.status == 200

        - name: "Print NSE ticker list"
          ansible.builtin.debug:
             msg: "load_ticker table is loaded with {{ db_results0.rowcount }} rows"

        - name: "DB: identify new tickers"
          community.postgresql.postgresql_query:
             db:          "{{ db.database }}"
             login_host:  "{{ db.hostname }}"
             login_user:  "{{ db.username }}"
             login_password: "{{ db.pwd }}"
             query: |
                update nse.load_stocks set is_new = true where ticker not in (select ticker from nse.stocks);
                insert into nse.stocks(ticker, name, series, date_of_listing, paid_up_value, market_lot, isin, face_value, crd_date,upd_date,crd_by,upd_by) 
                select ticker, name, series, date_of_listing::date, paid_up_value, market_lot, isin, face_value, crd_date,upd_date,crd_by,upd_by from nse.load_stocks where is_new is true;
          register: db_results1

        - name: "stop audit log"
          ansible.builtin.include_tasks:
             file: "suppl/common_audit.yml"
          vars:
             - condition: "stop"