---
# tasks file for roles/dailyStockPrice

   - name: "initialize job_id"
     ansible.builtin.set_fact:
        job_id: "{{ lookup('pipe', 'date  \"+%Y%m%d_%H%M%S\"') }}"
        job_name: "{{ dailyStockPrices.job_name }}"
        output: "{{ app_output_fldr }}"
        debug: "{{ bulkStockPrices.debug }}"
        doLogging: false

   - name: "start audit log"
     ansible.builtin.include_tasks:
        file: "suppl/common_audit.yml"
     vars:
        - condition: "start"
     when: doLogging

#   - name: "create query for lifecycle record"
#     ansible.builtin.set_fact:
#        query: "{{ bulkStockPrices.query }} and to_char(start_date,'YYYY') = '{{year}}'  limit {{ bulkStockPrices.tickerCount }}"
#     when: year is defined

#   - name: "DB: Get Stock bulk load dates"
#     community.postgresql.postgresql_query:
#        db:          "{{ db.database }}"
#        login_host:  "{{ db.hostname }}"
#        login_user:  "{{ db.username }}"
#        login_password: "{{ db.pwd }}"
#        query: "{{ query }};"
#     register: var_lc_stock_details

   # - name: "Print RESULT"
   #   ansible.builtin.debug:
   #      msg: "debug = {{ var_lc_stock_details }}"

   - name: "Loading table load_stock_details"
     ansible.builtin.include_tasks:
        file: suppl/loadDailyStockPrice_supplement.yml
     vars:
      #   start_date: "{{ item.start_date[8:10]+'-'+item.start_date[5:7]+'-'+item.start_date[0:4]  }}"
      #   end_date:   "{{ item.end_date[8:10]  +'-'+item.end_date[5:7]  +'-'+item.end_date[0:4] }}"
        ticker: "INFY"
        tsymbol: "INFY"
        nse_url: "{{ nse.url }}"
   #   loop: "{{ var_lc_stock_details.query_result }}"

   - name: "stop audit log"
     ansible.builtin.include_tasks:
        file: "suppl/common_audit.yml"
     vars:
        - condition: "stop"
     when: doLogging
