---
# defaults file for roles/dailyStockPrices

dailyStockPrices:
   job_name: "dailyStockPrice.yml"
   output: "{{app_output_fldr}}/output"
   debug: false
   query: |
      select lc.ticker from {{db.schema}}.load_daily_stock_dates lc where is_loaded=false
   tickerCount: 20

