---
# defaults file for roles/dailyStockPrices

dailyStockPrices:
   job_name: "dailyStockPrice.yml"
   output: "{{app_output_fldr}}/output"
   debug: false
   query: |
      select lc.ticker,
      ''||lc.start_date start_date, ''||lc.end_date end_date
      from {{db.schema}}.load_bulk_stock_dates lc
      where is_loaded=false   
   tickerCount: 20

