---
# defaults file for roles/ticker
# app_root: /app/momentum1
# app_logs_fldr: "{{ app_root }}/logs"
# app_scripts_fldr: "{{ app_root }}/scripts"
# app_output_fldr: "{{ app_root }}/output"

ticker:
   job_name: "loadTickerTable.yml"
   output: "{{playbook_dir}}/output"
   debug: false
   query_script: |
      update {{db.schema}}.load_stocks set is_new = true where ticker not in (select ticker from {{db.schema}}.stocks);
      insert into {{db.schema}}.stocks(ticker, name, series, date_of_listing, paid_up_value, market_lot, isin, face_value, crd_date,upd_date,crd_by,upd_by) 
      select ticker, name, series, date_of_listing::date, paid_up_value, market_lot, isin, face_value, crd_date,upd_date,crd_by,upd_by from {{db.schema}}.load_stocks where is_new is true;

nse:
   url: "https://www.nseindia.com"
   tickerUrl: "https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv"

# db:
#    hostname: "192.168.1.16"
#    username: "nse"
#    pwd: "nse"
#    database: "kse"